### ISSUE TITLE
Pull request 

### ISSUE THREAD

**Issue by abraham-ny** [pycorer/easygit#2]
Please review the pull request @xandortelvanyx  @poxldivxi

**Comment by xandortelvanyx** [comment]
Thank you for your contribution @abummoja .

**Comment by abraham-ny** [comment]
@xandortelvanyx  I'd like to join your company ximilsoft. Also, the Facebook project seems interesting, I'd like to see what I can contribute.

**Comment by xandortelvanyx** [comment]
When click 'Enter' to open VSCode, it always show: "**Failed to open Visual Studio Code: name 'find_vscode' is not defined**".

![2024-09-22_095640](https://github.com/user-attachments/assets/8da9a1a9-c9f4-4850-9f3f-a5a7405e8ebd)

**Comment by abraham-ny** [comment]
> When click 'Enter' to open VSCode, it always show: "**Failed to open Visual Studio Code: name 'find_vscode' is not defined**".
> 
> ![2024-09-22_095640](https://github.com/user-attachments/assets/8da9a1a9-c9f4-4850-9f3f-a5a7405e8ebd)
> 

Didn't expect that... Working on it.

**Comment by abraham-ny** [comment]
Fixed with the latest commit
